from enum import StrEnum


class SignalAction(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class ExecutionStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"

    DRY_RUN_APPROVED = "DRY_RUN_APPROVED"
    DRY_RUN_REJECTED = "DRY_RUN_REJECTED"
    EXECUTED = "EXECUTED"
    EXECUTED_PARTIAL = "EXECUTED_PARTIAL"
    RECOVERED_EXECUTED = "RECOVERED_EXECUTED"

    REJECTED_STALE = "REJECTED_STALE"
    REJECTED_FUTURE_TIMESTAMP = "REJECTED_FUTURE_TIMESTAMP"
    REJECTED_SYMBOL = "REJECTED_SYMBOL"
    REJECTED_SYMBOL_UNAVAILABLE = "REJECTED_SYMBOL_UNAVAILABLE"
    REJECTED_RISK = "REJECTED_RISK"
    REJECTED_STOP_LOSS = "REJECTED_STOP_LOSS"
    REJECTED_SPREAD = "REJECTED_SPREAD"
    REJECTED_DAILY_LOSS = "REJECTED_DAILY_LOSS"
    REJECTED_DAILY_TRADE_LIMIT = "REJECTED_DAILY_TRADE_LIMIT"
    REJECTED_POSITION_LIMIT = "REJECTED_POSITION_LIMIT"
    REJECTED_VOLUME = "REJECTED_VOLUME"
    REJECTED_VOLUME_BELOW_MINIMUM = "REJECTED_VOLUME_BELOW_MINIMUM"
    REJECTED_ORDER_CHECK = "REJECTED_ORDER_CHECK"

    FAILED_MT5_UNAVAILABLE = "FAILED_MT5_UNAVAILABLE"
    FAILED_MT5_STATE_UNKNOWN = "FAILED_MT5_STATE_UNKNOWN"
    FAILED_BROKER_TIME_UNKNOWN = "FAILED_BROKER_TIME_UNKNOWN"
    FAILED_ORDER_SEND = "FAILED_ORDER_SEND"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


TERMINAL_STATUSES = {
    ExecutionStatus.DRY_RUN_APPROVED,
    ExecutionStatus.DRY_RUN_REJECTED,
    ExecutionStatus.EXECUTED,
    ExecutionStatus.EXECUTED_PARTIAL,
    ExecutionStatus.RECOVERED_EXECUTED,
    ExecutionStatus.REJECTED_STALE,
    ExecutionStatus.REJECTED_FUTURE_TIMESTAMP,
    ExecutionStatus.REJECTED_SYMBOL,
    ExecutionStatus.REJECTED_SYMBOL_UNAVAILABLE,
    ExecutionStatus.REJECTED_RISK,
    ExecutionStatus.REJECTED_STOP_LOSS,
    ExecutionStatus.REJECTED_SPREAD,
    ExecutionStatus.REJECTED_DAILY_LOSS,
    ExecutionStatus.REJECTED_DAILY_TRADE_LIMIT,
    ExecutionStatus.REJECTED_POSITION_LIMIT,
    ExecutionStatus.REJECTED_VOLUME,
    ExecutionStatus.REJECTED_VOLUME_BELOW_MINIMUM,
    ExecutionStatus.REJECTED_ORDER_CHECK,
    ExecutionStatus.FAILED_ORDER_SEND,
    ExecutionStatus.FAILED_MT5_STATE_UNKNOWN,
    ExecutionStatus.FAILED_BROKER_TIME_UNKNOWN,
    ExecutionStatus.REVIEW_REQUIRED,
}
